name: otobix_inspection_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  get: ^4.7.3
  http: ^1.6.0
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4
  delightful_toast: ^1.1.0
  firebase_core: ^4.3.0
  socket_io_client: ^3.1.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  change_app_package_name: ^1.5.0
  persistent_bottom_nav_bar: ^6.2.1
  video_player: ^2.10.1
  chewie: ^1.13.0 
  video_thumbnail: ^0.5.6
  file_picker: ^10.3.8
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4
  path_provider: ^2.1.5
  path: ^1.9.1
  connectivity_plus: ^7.0.0
  flutter_native_video_trimmer: ^1.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # ✅ App launcher icon plugin
  flutter_launcher_icons: ^0.14.4

# ✅ flutter_launcher_icons config
# IMPORTANT: apni logo file ka exact name yahan set karo
flutter_icons:
  android: true
  ios: true

  # ✅ Your logo path (change filename if needed)
  image_path: "assets/images/applogo1.png"

  # ✅ Android 8+ adaptive icon (recommended)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/applogo1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
